// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Performs sentiment analysis on context entries to provide insights into the user's mood.
 *
 * - analyzeContextSentiment - A function that analyzes the sentiment of context entries.
 * - AnalyzeContextSentimentInput - The input type for the analyzeContextSentiment function.
 * - AnalyzeContextSentimentOutput - The return type for the analyzeContextSentiment function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeContextSentimentInputSchema = z.object({
  contextEntries: z
    .array(z.string())
    .describe('An array of context entries to analyze.'),
});
export type AnalyzeContextSentimentInput = z.infer<
  typeof AnalyzeContextSentimentInputSchema
>;

const AnalyzeContextSentimentOutputSchema = z.object({
  overallSentiment: z
    .string()
    .describe('The overall sentiment of the context entries.'),
  sentimentBreakdown: z
    .array(z.object({entry: z.string(), sentiment: z.string()}))
    .describe(
      'A breakdown of the sentiment of each context entry, including the entry and its sentiment.'
    ),
});

export type AnalyzeContextSentimentOutput = z.infer<
  typeof AnalyzeContextSentimentOutputSchema
>;

export async function analyzeContextSentiment(
  input: AnalyzeContextSentimentInput
): Promise<AnalyzeContextSentimentOutput> {
  return analyzeContextSentimentFlow(input);
}

const prompt = ai.definePrompt({
  name: 'analyzeContextSentimentPrompt',
  input: {schema: AnalyzeContextSentimentInputSchema},
  output: {schema: AnalyzeContextSentimentOutputSchema},
  prompt: `You are an AI sentiment analyzer. Analyze the sentiment of the following context entries and provide an overall sentiment, and a breakdown of the sentiment of each context entry. 

Context Entries:
{{#each contextEntries}}- {{{this}}}
{{/each}}`,
});

const analyzeContextSentimentFlow = ai.defineFlow(
  {
    name: 'analyzeContextSentimentFlow',
    inputSchema: AnalyzeContextSentimentInputSchema,
    outputSchema: AnalyzeContextSentimentOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
